language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - coverage run --source='api' manage.py test --settings=api.config.test_settings
  - coverage report -m --omit="*/test*"
after_success:
  - codecov
