version: '2'
services:
  db:
    image: postgres
    volumes:
      - data:/data/db
    env_file:
      - .env
  web:
    build: .
    command: python run_server.py
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  data:
    external:
      name: "postgres"
