version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: python api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
