# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'SUCCESS'), (3, 'FAILED')], default=0)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalStrategy',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'SUCCESS'), (3, 'FAILED')], default=0)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('turns', models.IntegerField()),
                ('noise', models.FloatField()),
                ('player_list', models.ManyToManyField(to='core.InternalStrategy')),
            ],
        ),
        migrations.CreateModel(
            name='MoranDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('turns', models.IntegerField()),
                ('noise', models.FloatField()),
                ('mode', models.CharField(max_length=2)),
                ('player_list', models.ManyToManyField(to='core.InternalStrategy')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=255)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'SUCCESS'), (3, 'FAILED')], default=0)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('turns', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('noise', models.FloatField()),
                ('with_morality', models.BooleanField()),
                ('player_list', models.ManyToManyField(to='core.InternalStrategy')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TournamentDefinition'),
        ),
        migrations.AddField(
            model_name='match',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MatchDefinition'),
        ),
    ]
