# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170423_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoranProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'SUCCESS'), (3, 'FAILED')], default=0)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MoranDefinition')),
            ],
        ),
    ]
