# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170424_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='moranprocess',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
